const topicDetails = [
  {
    id: "1",
    topicName: "Array",
    topic: "Array",
    qCount: "8",
    routes: "array",
  },
  {
    id: "2",
    topicName: "Strings",
    topic: "String",
    qCount: "8",
    routes: "strings",
  },
  {
    id: "3",
    topicName: "LinkedList",
    topic: "LinkedList",
    qCount: "8",
    routes: "linkedlist",
  },
  {
    id: "4",
    topicName: "Sorting",
    topic: "Searching & Sorting",
    qCount: "8",
    routes: "sorting",
  },
  {
    id: "5",
    topicName: "BST",
    topic: "Binary Search Trees",
    qCount: "8",
    routes: "bst",
  },
  {
    id: "6",
    topicName: "Backtracking",
    topic: "BackTracking",
    qCount: "8",
    routes: "backtracking",
  },
  {
    id: "7",
    topicName: "Stack",
    topic: "Stacks",
    qCount: "8",
    routes: "stack",
  },
  {
    id: "8",
    topicName: "Heap",
    topic: "Heap",
    qCount: "8",
    routes: "heap",
  },
  {
    id: "9",
    topicName: "Graph",
    topic: "Graph",
    qCount: "8",
    routes: "graph",
  },
];
export default topicDetails;
